### ISSUE TITLE
How can I run NPM commands on "watch"?

### ISSUE THREAD

**Issue by mcranston18** [keymetrics/docker-pm2#39]
Hey maintainers, thanks very much for your hard work!

I would like to run an NPM command every time pm2-docker restarts from a "watch". This is my package.json file:
```
{
  "name": "my app",
  "scripts": {
    "eslint": "eslint */**.js",
    "start": "pm2-docker process.yml --watch"
  }
}
```
And then I have a `process.yml` file:
```
apps:
  - script   : 'app.js'
    exec_mode: 'cluster'
    instances: 4
```

The `--watch` flag run correctly every time I update my JS files, but I would also like to run `npm run lint` on each watch.

Is this possible?

**Comment by simonepri** [comment]
Hi @mcranston18 find the documentation of the `--watch` command [here](http://pm2.keymetrics.io/docs/usage/watch-and-restart/)

As you can see is not possible to execute a custom command each time the watch is triggered.

It seems quite odd to me that you want to lint your app on reload.
I mean there are plenty better ways to do it if you need it for development purposes.

I'm closing this issue since is not related with this repo.
The `pm2-docker`'s repo is [this](https://github.com/Unitech/pm2).
